github:
    name:           hiqdev/minii-helpers

package:
    type:           library
    name:           helpers
    namespace:      yii\helpers
    title:          minii Helpers
    keywords:       minii, helpers
    description:    |
        [minii](https://github.com/hiqdev/minii-core) is mini version of [Yii2](http://yiiframework.com/), supposed to be fully compatible.
        This package provides yii\helpers.

require:
    minii/hidev-vendor: "*"
    hiqdev/hidev-php:   "*"
